version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  open-pull-requests-limit: 10
  schedule:
    interval: "weekly"
  groups:
    k8s.io:
      patterns:
        - "k8s.io/*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
