apiVersion: perses.dev/v1alpha1
kind: PersesDatasource
metadata:
  name: thanos-querier-proxy-datasource
  namespace: perses-dev
spec:
  display:
    name: "Thanos Querier Datasource using Proxy"
  default: true
  plugin:
    kind: "PrometheusDatasource"
    spec:
      proxy:
        kind: HTTPProxy
        spec:
          url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
