version: 1
timeout: '1m'

validators:
  # timeout
  - regex: 'github\.com'
    type: 'ignore'
  # code 500
  - regex: 'slack\.com'
    type: 'ignore'
  # timeout
  - regex: 'slack\.cncf\.io'
    type: 'ignore'
