FROM golang:1.25-alpine AS build-env

RUN apk add --update --no-cache make bash mailcap jq git findutils curl

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY Makefile ./
RUN make build-tools

COPY . .

RUN make build

FROM gcr.io/distroless/static-debian12

LABEL maintainer="The Perses Authors <perses-team@googlegroups.com>"

USER 65532:65532

COPY --from=build-env --chown=65532:65532 /app/bin/manager  /bin/manager
COPY --chown=65532:65532 LICENSE                            /LICENSE
COPY --from=build-env --chown=65532:65532                   /etc/mime.types /etc/mime.types

EXPOSE     8080
ENTRYPOINT [ "/bin/manager" ]
