version: 2
builds:
  - id: "operator"
    main: ./main.go
    binary: "/bin/manager"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
    env:
      - CGO_ENABLED=0
archives:
  - id: "default"
    ids:
      - "operator"
    formats:
      - "tar.gz"
    files:
      - LICENSE
      - README.md
release:
  github:
    owner: "perses"
    name: "perses-operator"
  ids:
    - "default"
  prerelease: auto
  name_template: "{{ .Version }} / {{ .Env.DATE }}"

changelog:
  use: github
