apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: perses-operator
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/name: perses-operator
    app.kubernetes.io/part-of: perses-operator
    app.kubernetes.io/version: v0.2.0
  name: perses-operator-leader-election-role
  namespace: perses-dev
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
