apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: perses-operator
    app.kubernetes.io/instance: perses-viewer-role
    app.kubernetes.io/name: perses-operator
    app.kubernetes.io/part-of: perses-operator
    app.kubernetes.io/version: v0.2.0
  name: perses-viewer-role
rules:
- apiGroups:
  - perses.dev
  resources:
  - perses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - perses.dev
  resources:
  - perses/status
  verbs:
  - get
