apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
  name: perses-operator.v0.1.0
  namespace: perses
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Perses is the Schema for the perses API
      displayName: Perses
      kind: Perses
      name: perses.perses.dev
      specDescriptors:
      - displayName: Config
        path: config
      - displayName: Container Port
        path: containerPort
      statusDescriptors:
      - displayName: Conditions
        path: conditions
      version: v1alpha1
  description: The Perses Operator deploys and manages Perses instances, dashboards
    and datasources.
  displayName: Perses Operator
  icon:
  - base64data: /9j/4AAQSkZJRgABAQEBLAEsAAD//gAIUGVyc2Vz/+ICsElDQ19QUk9GSUxFAAEBAAACoGxjbXMEQAAAbW50clJHQiBYWVogB+gADAACAAkAOgAsYWNzcEFQUEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1sY21zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANZGVzYwAAASAAAABAY3BydAAAAWAAAAA2d3RwdAAAAZgAAAAUY2hhZAAAAawAAAAsclhZWgAAAdgAAAAUYlhZWgAAAewAAAAUZ1hZWgAAAgAAAAAUclRSQwAAAhQAAAAgZ1RSQwAAAhQAAAAgYlRSQwAAAhQAAAAgY2hybQAAAjQAAAAkZG1uZAAAAlgAAAAkZG1kZAAAAnwAAAAkbWx1YwAAAAAAAAABAAAADGVuVVMAAAAkAAAAHABHAEkATQBQACAAYgB1AGkAbAB0AC0AaQBuACAAcwBSAEcAQm1sdWMAAAAAAAAAAQAAAAxlblVTAAAAGgAAABwAUAB1AGIAbABpAGMAIABEAG8AbQBhAGkAbgAAWFlaIAAAAAAAAPbWAAEAAAAA0y1zZjMyAAAAAAABDEIAAAXe///zJQAAB5MAAP2Q///7of///aIAAAPcAADAblhZWiAAAAAAAABvoAAAOPUAAAOQWFlaIAAAAAAAACSfAAAPhAAAtsRYWVogAAAAAAAAYpcAALeHAAAY2XBhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbY2hybQAAAAAAAwAAAACj1wAAVHwAAEzNAACZmgAAJmcAAA9cbWx1YwAAAAAAAAABAAAADGVuVVMAAAAIAAAAHABHAEkATQBQbWx1YwAAAAAAAAABAAAADGVuVVMAAAAIAAAAHABzAFIARwBC/9sAQwADAgIDAgIDAwMDBAMDBAUIBQUEBAUKBwcGCAwKDAwLCgsLDQ4SEA0OEQ4LCxAWEBETFBUVFQwPFxgWFBgSFBUU/9sAQwEDBAQFBAUJBQUJFA0LDRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU/8IAEQgAUABQAwERAAIRAQMRAf/EABwAAQABBQEBAAAAAAAAAAAAAAAHAQQFBggCA//EABsBAQABBQEAAAAAAAAAAAAAAAADAQIEBgcF/9oADAMBAAIQAxAAAAGcbvfiSXdqKgC8pjz7Dze7QiF797gmbogAFyj64xuKZ154AHlXzSoAH0raBaUm4uy+8467KAAmCDR+jYuXChCcm/YyuWABINms7Bb5seybMABc0ilWzT/a0QHJ0eDsjoQAFaU7IxOF7I8sfOl2Bu9EAC5pFmWCBFF+4wtLvu9Wa90NFzIAACNrtphebfd9j1udI+egAAf/xAAjEAAABQMFAQEBAAAAAAAAAAAAAQMEBQIGFwcQExYgFREU/9oACAEBAAEFArnudO3UT1Kkv3JUmMlSYyVJjJUmGupjslWjpN6221BgnL4/nuh890Pnuh890PnughDvnKsHHnFxPk6iIclI5KRyUjkpHJT4drfzNX8g4k3HnT2XcUyexl+k/wBNaFXGMVhjFYYxWGMVhjFYW1aKNvnMzbWCbZMYjJjEZMYjJjEZMYhvqRHKq0V0qUbamNFjW8kR1HbjZVnB7KJ0q0ddix12LHXYsddix12LDeGYNVN74uZeGLtkuLTvJ6pJ+7xtaufoOxpsjtWx3LJ/7//EADQRAAAEAgcFBwMFAAAAAAAAAAABAgMEUwUREhaRodEGFBUxURAgIUFSYeETMHEiIzJCgf/aAAgBAwEBPwGiaJXSiz8aklzMFspBea1ZaC6kF61YloLqQXrViWgupBetWJaC6kF61YloHtk2DT+y4ZH71HoHmlsOKac5l27M0izDW4d46q/EhvUPMLEhvTEwsSG9MTCxIb0xMLEhvTEwsSDkfCtJtrcKr8ikIkoyKcfLkZ96qsWT6CyfQWT6CyfQWT6dxlH1XEt9TENCtQjZNMpqLvbTQTJw+9EVSiPHt5CG2rWhskvt2j61i9qJOfwL2ok5/AvaiTn8C9qJOfwL2ok5/ApWmnKTqRVZQXkIGj36Qc+myWhC6cVMTnoLpxUxOegunFTE56C6cVMTnoLpxUxOegc2WjEJNSVEfsFJNJ2Vc+3ZN5skuM/25/53jMiKsxSjrb8a641yM+1KjQdpJ+I4nHTlYmOJx05WJjicdOViY4nHTlYmOJx05WJhyOink2HHVGX5PubP0S1Hmp5/+KfL3HBaPkkKaoKGRDKfhk2TTmX2KDpdNGqUh0v0KyBbQ0ZNyVoKY2gZiGDh4Xxr5n9j/8QAIREAAgIBBAMBAQAAAAAAAAAAAAECEhMRIFFhAyEwMUD/2gAIAQIBAT8BSsY0Y0Y0Y0Y0Px8bIPT9LR5LR5LR5LR5LR5Lx5/hSS3TSXvYptGToydGToydGTocrC9lGUZRlGUZR7PH+/PVmrNWas1e2MbGOJKKS1XwjKpdEpa+vh//xAA4EAABAwECCAwFBQAAAAAAAAABAAIDBBE0EhMhMTJBkpMQIDM1QmFxkaHR0uEUMFFysSNDYoPw/9oACAEBAAY/Ao/08dPJostsHaVkgpbPtd6lyFJsO9S5Ck2HepchSbDvUuQpNh3qQ+JpYXx68Va0/kqKeI4UcjcJp4YKymjdNi24D2Nz9qu02wVdpdgq7S7BV2l2CrtLsFCOOkmc4/wKpqVxtdG3L28bKbFpDvWkO9aQ71pDvWkO/iTS2YWLYXWfWxOmqJDI8/XV2cb4Evc+ne0kNPRI4bDlCc+lqsTGf23stsV/Zu/dX9m791f2bv3V/Zu/dX9m7906XGY+pcLMOywAdSxtS45dFjc7ldajw81dajw81dajw81dajw81dajw801r4p4WnpkCwIOaQ5pFoI18NJUWEwBpZ9p/wB+OMABaTqVHDPyrWZQdXVwlr2h7TnDgubqbdBc3026C5vpt0FzfTboLm+m3QWMho4InjpNjAPEhpqQhk0gwi/PghX+VRUtZLj4pjghzs7Tq+RFLTua2piyWOzOCudv9rPNR1ldgsxWVsQNpt6/kf/EACUQAQABAQcEAwEAAAAAAAAAAAERACAhMUGBwfAQUWHxMHGR0f/aAAgBAQABPyHPQ8MBilS0PILWWLFixXyMyKayVA3bAXPWdAAMgmQGeLOlci2rg21cG2rg21cG2plRwEBqtxQeY1jJK9jxLawE+zac5znY9YVag/YmKUv83rvAZFokpcJCTJ2MvzqDBIQjU/8A8mgxnCvcqe5U9yp7lT3KjeU1fjQvoQdOCS3gtBBBBBI3GFT7IZo15kpA59QymiYSzf8Ado5ZEAxansB5zMaBDTqES4lB0riu1c92rnu1c92rnu1C8DRhrFhWB3kpYIHNZ/K94fyro9GA3uMRbtfgAiiblOU5JvSgCDMvK5Vu23ei67x8H//aAAwDAQACAAMAAAAQsSSokf8A/wBSSSRJJCTQkkiQnbbV221iTEknqTSSTSSwSSST7ySST//EACQRAQABAgUFAQEBAAAAAAAAAAERACExQVFhkRAgccHwgbHR/9oACAEDAQE/EMsfsSy4AWva+nBUIufPbq1atWl0rYbYCPN/FC1Do+TrDHOI2JiEXLKJtjnj9J7r5T3XynuvlPdfKe6bhjY8BK+AmgBiUeCxO8F9+4WArdVuq3Vbqt12SsxETpLE0GAOXdc3fujKEFLQbQ6o3HGJ6iqTGoEjkhPkhvrD+Fb7jTfcab7jTfcab7jQ4ZibpV1WDeCOaykrq2DVfRK6dyCCCCD8syKL4kDlKThAYRyTqskGg1YRbw/3uRJAVihSHXKf1v8AvUKgGCWT9r673X13uvrvdfXe6+u90+UsljhewxVQDBOJlLwEWMZxtf7H/agCKUFjMszCF5NITTvVMwNsUZxmOediNFQLCpPdgoIRsN1cLhB5t3//xAAlEQEAAgEBCAIDAAAAAAAAAAABABFhIDFBcYGR4fDxMFEQIaH/2gAIAQIBAT8QdUQo/bpAPsaBb9pidZidZidZidZidYhuRbV12SyWSyWaFouG0aqwb9AlJct7dpb27S3t2lvbtLe3aMrYFUTh+cpw/OU4fnKcPzlOH5yiJehAh36lAti2r+avbMzMzMzMzMzFXa6CTe6YP6/DosLUFNsM0Pg//8QAIxABAQABAwQDAAMAAAAAAAAAAREAICExQVFh8RBxkYGhwf/aAAgBAQABPxAKFcbYLYGBQA3XtFHO+dyg8sX8NJgwYMVkIBvBuiRTg2vc5x+iGFJUo8JwnRPm/heL4zuKEb9kqIqJJ0dO3bt2417IK8gA8qBhDnvkZNPQgeA1FiU8SM9Yz1jPWM9Yz1jBAIiPCfLlgUKpYfcmM+HSpr4gdA1P2OdLNeYFBsr8j8pAUR5HDYrNKqqM3sEp3dVatWrVlT5sBRbUWFVbNplZgEjyoyG21VApXcxr/nl6/L1+Xr8vX5fZUAfQ8fQ/WA+U0KoE5Ebfkh9nVu92SgagIGGqiwAOXCcMuqVR5+QILyEP2Vsn3iyulxQoUKf0ayuRR/Gg4JjwYCJBuRgtq0XVzTVB+QnADYEN4IkR1q9CNWDQFRU6bhlo5xEJ/kUP6YpQrbS0KAKpSqHAb6//2Q==
    mediatype: image/jpeg
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - monitoring
  - logs
  - traces
  - metrics
  - dashboards
  links:
  - name: Perses Operator
    url: https://perses.dev
  maintainers:
  - email: gbernal@redhat.com
    name: Gabriel Bernal
  - email: augustin.husson@amadeus.com
    name: Augustin Husson
  maturity: alpha
  provider:
    name: Perses
    url: perses.dev
  version: 0.1.0
