//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 The Perses Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha2 "github.com/perses/perses-operator/api/v1alpha2"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BasicAuth)(nil), (*v1alpha2.BasicAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BasicAuth_To_v1alpha2_BasicAuth(a.(*BasicAuth), b.(*v1alpha2.BasicAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BasicAuth)(nil), (*BasicAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BasicAuth_To_v1alpha1_BasicAuth(a.(*v1alpha2.BasicAuth), b.(*BasicAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Certificate)(nil), (*v1alpha2.Certificate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Certificate_To_v1alpha2_Certificate(a.(*Certificate), b.(*v1alpha2.Certificate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Certificate)(nil), (*Certificate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Certificate_To_v1alpha1_Certificate(a.(*v1alpha2.Certificate), b.(*Certificate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Client)(nil), (*v1alpha2.Client)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Client_To_v1alpha2_Client(a.(*Client), b.(*v1alpha2.Client), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Client)(nil), (*Client)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Client_To_v1alpha1_Client(a.(*v1alpha2.Client), b.(*Client), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Dashboard)(nil), (*v1alpha2.Dashboard)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Dashboard_To_v1alpha2_Dashboard(a.(*Dashboard), b.(*v1alpha2.Dashboard), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Dashboard)(nil), (*Dashboard)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Dashboard_To_v1alpha1_Dashboard(a.(*v1alpha2.Dashboard), b.(*Dashboard), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Datasource)(nil), (*v1alpha2.Datasource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Datasource_To_v1alpha2_Datasource(a.(*Datasource), b.(*v1alpha2.Datasource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Datasource)(nil), (*Datasource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Datasource_To_v1alpha1_Datasource(a.(*v1alpha2.Datasource), b.(*Datasource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DatasourceSpec)(nil), (*v1alpha2.DatasourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DatasourceSpec_To_v1alpha2_DatasourceSpec(a.(*DatasourceSpec), b.(*v1alpha2.DatasourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubernetesAuth)(nil), (*v1alpha2.KubernetesAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KubernetesAuth_To_v1alpha2_KubernetesAuth(a.(*KubernetesAuth), b.(*v1alpha2.KubernetesAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.KubernetesAuth)(nil), (*KubernetesAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_KubernetesAuth_To_v1alpha1_KubernetesAuth(a.(*v1alpha2.KubernetesAuth), b.(*KubernetesAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metadata)(nil), (*v1alpha2.Metadata)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Metadata_To_v1alpha2_Metadata(a.(*Metadata), b.(*v1alpha2.Metadata), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Metadata)(nil), (*Metadata)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Metadata_To_v1alpha1_Metadata(a.(*v1alpha2.Metadata), b.(*Metadata), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OAuth)(nil), (*v1alpha2.OAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OAuth_To_v1alpha2_OAuth(a.(*OAuth), b.(*v1alpha2.OAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.OAuth)(nil), (*OAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_OAuth_To_v1alpha1_OAuth(a.(*v1alpha2.OAuth), b.(*OAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Perses)(nil), (*v1alpha2.Perses)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Perses_To_v1alpha2_Perses(a.(*Perses), b.(*v1alpha2.Perses), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Perses)(nil), (*Perses)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Perses_To_v1alpha1_Perses(a.(*v1alpha2.Perses), b.(*Perses), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesConfig)(nil), (*v1alpha2.PersesConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesConfig_To_v1alpha2_PersesConfig(a.(*PersesConfig), b.(*v1alpha2.PersesConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PersesConfig)(nil), (*PersesConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesConfig_To_v1alpha1_PersesConfig(a.(*v1alpha2.PersesConfig), b.(*PersesConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesDashboard)(nil), (*v1alpha2.PersesDashboard)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesDashboard_To_v1alpha2_PersesDashboard(a.(*PersesDashboard), b.(*v1alpha2.PersesDashboard), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PersesDashboard)(nil), (*PersesDashboard)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesDashboard_To_v1alpha1_PersesDashboard(a.(*v1alpha2.PersesDashboard), b.(*PersesDashboard), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesDashboardList)(nil), (*v1alpha2.PersesDashboardList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesDashboardList_To_v1alpha2_PersesDashboardList(a.(*PersesDashboardList), b.(*v1alpha2.PersesDashboardList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PersesDashboardList)(nil), (*PersesDashboardList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesDashboardList_To_v1alpha1_PersesDashboardList(a.(*v1alpha2.PersesDashboardList), b.(*PersesDashboardList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesDashboardStatus)(nil), (*v1alpha2.PersesDashboardStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesDashboardStatus_To_v1alpha2_PersesDashboardStatus(a.(*PersesDashboardStatus), b.(*v1alpha2.PersesDashboardStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PersesDashboardStatus)(nil), (*PersesDashboardStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesDashboardStatus_To_v1alpha1_PersesDashboardStatus(a.(*v1alpha2.PersesDashboardStatus), b.(*PersesDashboardStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesDatasource)(nil), (*v1alpha2.PersesDatasource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesDatasource_To_v1alpha2_PersesDatasource(a.(*PersesDatasource), b.(*v1alpha2.PersesDatasource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PersesDatasource)(nil), (*PersesDatasource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesDatasource_To_v1alpha1_PersesDatasource(a.(*v1alpha2.PersesDatasource), b.(*PersesDatasource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesDatasourceList)(nil), (*v1alpha2.PersesDatasourceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesDatasourceList_To_v1alpha2_PersesDatasourceList(a.(*PersesDatasourceList), b.(*v1alpha2.PersesDatasourceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PersesDatasourceList)(nil), (*PersesDatasourceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesDatasourceList_To_v1alpha1_PersesDatasourceList(a.(*v1alpha2.PersesDatasourceList), b.(*PersesDatasourceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesDatasourceStatus)(nil), (*v1alpha2.PersesDatasourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesDatasourceStatus_To_v1alpha2_PersesDatasourceStatus(a.(*PersesDatasourceStatus), b.(*v1alpha2.PersesDatasourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PersesDatasourceStatus)(nil), (*PersesDatasourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesDatasourceStatus_To_v1alpha1_PersesDatasourceStatus(a.(*v1alpha2.PersesDatasourceStatus), b.(*PersesDatasourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesList)(nil), (*v1alpha2.PersesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesList_To_v1alpha2_PersesList(a.(*PersesList), b.(*v1alpha2.PersesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PersesList)(nil), (*PersesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesList_To_v1alpha1_PersesList(a.(*v1alpha2.PersesList), b.(*PersesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesService)(nil), (*v1alpha2.PersesService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesService_To_v1alpha2_PersesService(a.(*PersesService), b.(*v1alpha2.PersesService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PersesService)(nil), (*PersesService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesService_To_v1alpha1_PersesService(a.(*v1alpha2.PersesService), b.(*PersesService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesSpec)(nil), (*v1alpha2.PersesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesSpec_To_v1alpha2_PersesSpec(a.(*PersesSpec), b.(*v1alpha2.PersesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersesStatus)(nil), (*v1alpha2.PersesStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PersesStatus_To_v1alpha2_PersesStatus(a.(*PersesStatus), b.(*v1alpha2.PersesStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.PersesStatus)(nil), (*PersesStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesStatus_To_v1alpha1_PersesStatus(a.(*v1alpha2.PersesStatus), b.(*PersesStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretSource)(nil), (*v1alpha2.SecretSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecretSource_To_v1alpha2_SecretSource(a.(*SecretSource), b.(*v1alpha2.SecretSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.SecretSource)(nil), (*SecretSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SecretSource_To_v1alpha1_SecretSource(a.(*v1alpha2.SecretSource), b.(*SecretSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StorageConfiguration)(nil), (*v1alpha2.StorageConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StorageConfiguration_To_v1alpha2_StorageConfiguration(a.(*StorageConfiguration), b.(*v1alpha2.StorageConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.StorageConfiguration)(nil), (*StorageConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_StorageConfiguration_To_v1alpha1_StorageConfiguration(a.(*v1alpha2.StorageConfiguration), b.(*StorageConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TLS)(nil), (*v1alpha2.TLS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TLS_To_v1alpha2_TLS(a.(*TLS), b.(*v1alpha2.TLS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.TLS)(nil), (*TLS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_TLS_To_v1alpha1_TLS(a.(*v1alpha2.TLS), b.(*TLS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Dashboard)(nil), (*v1alpha2.PersesDashboardSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Dashboard_To_v1alpha2_PersesDashboardSpec(a.(*Dashboard), b.(*v1alpha2.PersesDashboardSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.DatasourceSpec)(nil), (*DatasourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DatasourceSpec_To_v1alpha1_DatasourceSpec(a.(*v1alpha2.DatasourceSpec), b.(*DatasourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.PersesDashboardSpec)(nil), (*Dashboard)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesDashboardSpec_To_v1alpha1_Dashboard(a.(*v1alpha2.PersesDashboardSpec), b.(*Dashboard), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.PersesSpec)(nil), (*PersesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PersesSpec_To_v1alpha1_PersesSpec(a.(*v1alpha2.PersesSpec), b.(*PersesSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BasicAuth_To_v1alpha2_BasicAuth(in *BasicAuth, out *v1alpha2.BasicAuth, s conversion.Scope) error {
	if err := Convert_v1alpha1_SecretSource_To_v1alpha2_SecretSource(&in.SecretSource, &out.SecretSource, s); err != nil {
		return err
	}
	out.Username = in.Username
	out.PasswordPath = in.PasswordPath
	return nil
}

// Convert_v1alpha1_BasicAuth_To_v1alpha2_BasicAuth is an autogenerated conversion function.
func Convert_v1alpha1_BasicAuth_To_v1alpha2_BasicAuth(in *BasicAuth, out *v1alpha2.BasicAuth, s conversion.Scope) error {
	return autoConvert_v1alpha1_BasicAuth_To_v1alpha2_BasicAuth(in, out, s)
}

func autoConvert_v1alpha2_BasicAuth_To_v1alpha1_BasicAuth(in *v1alpha2.BasicAuth, out *BasicAuth, s conversion.Scope) error {
	if err := Convert_v1alpha2_SecretSource_To_v1alpha1_SecretSource(&in.SecretSource, &out.SecretSource, s); err != nil {
		return err
	}
	out.Username = in.Username
	out.PasswordPath = in.PasswordPath
	return nil
}

// Convert_v1alpha2_BasicAuth_To_v1alpha1_BasicAuth is an autogenerated conversion function.
func Convert_v1alpha2_BasicAuth_To_v1alpha1_BasicAuth(in *v1alpha2.BasicAuth, out *BasicAuth, s conversion.Scope) error {
	return autoConvert_v1alpha2_BasicAuth_To_v1alpha1_BasicAuth(in, out, s)
}

func autoConvert_v1alpha1_Certificate_To_v1alpha2_Certificate(in *Certificate, out *v1alpha2.Certificate, s conversion.Scope) error {
	if err := Convert_v1alpha1_SecretSource_To_v1alpha2_SecretSource(&in.SecretSource, &out.SecretSource, s); err != nil {
		return err
	}
	out.CertPath = in.CertPath
	out.PrivateKeyPath = in.PrivateKeyPath
	return nil
}

// Convert_v1alpha1_Certificate_To_v1alpha2_Certificate is an autogenerated conversion function.
func Convert_v1alpha1_Certificate_To_v1alpha2_Certificate(in *Certificate, out *v1alpha2.Certificate, s conversion.Scope) error {
	return autoConvert_v1alpha1_Certificate_To_v1alpha2_Certificate(in, out, s)
}

func autoConvert_v1alpha2_Certificate_To_v1alpha1_Certificate(in *v1alpha2.Certificate, out *Certificate, s conversion.Scope) error {
	if err := Convert_v1alpha2_SecretSource_To_v1alpha1_SecretSource(&in.SecretSource, &out.SecretSource, s); err != nil {
		return err
	}
	out.CertPath = in.CertPath
	out.PrivateKeyPath = in.PrivateKeyPath
	return nil
}

// Convert_v1alpha2_Certificate_To_v1alpha1_Certificate is an autogenerated conversion function.
func Convert_v1alpha2_Certificate_To_v1alpha1_Certificate(in *v1alpha2.Certificate, out *Certificate, s conversion.Scope) error {
	return autoConvert_v1alpha2_Certificate_To_v1alpha1_Certificate(in, out, s)
}

func autoConvert_v1alpha1_Client_To_v1alpha2_Client(in *Client, out *v1alpha2.Client, s conversion.Scope) error {
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(v1alpha2.BasicAuth)
		if err := Convert_v1alpha1_BasicAuth_To_v1alpha2_BasicAuth(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.BasicAuth = nil
	}
	if in.OAuth != nil {
		in, out := &in.OAuth, &out.OAuth
		*out = new(v1alpha2.OAuth)
		if err := Convert_v1alpha1_OAuth_To_v1alpha2_OAuth(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.OAuth = nil
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(v1alpha2.TLS)
		if err := Convert_v1alpha1_TLS_To_v1alpha2_TLS(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.TLS = nil
	}
	if in.KubernetesAuth != nil {
		in, out := &in.KubernetesAuth, &out.KubernetesAuth
		*out = new(v1alpha2.KubernetesAuth)
		if err := Convert_v1alpha1_KubernetesAuth_To_v1alpha2_KubernetesAuth(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.KubernetesAuth = nil
	}
	return nil
}

// Convert_v1alpha1_Client_To_v1alpha2_Client is an autogenerated conversion function.
func Convert_v1alpha1_Client_To_v1alpha2_Client(in *Client, out *v1alpha2.Client, s conversion.Scope) error {
	return autoConvert_v1alpha1_Client_To_v1alpha2_Client(in, out, s)
}

func autoConvert_v1alpha2_Client_To_v1alpha1_Client(in *v1alpha2.Client, out *Client, s conversion.Scope) error {
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuth)
		if err := Convert_v1alpha2_BasicAuth_To_v1alpha1_BasicAuth(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.BasicAuth = nil
	}
	if in.OAuth != nil {
		in, out := &in.OAuth, &out.OAuth
		*out = new(OAuth)
		if err := Convert_v1alpha2_OAuth_To_v1alpha1_OAuth(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.OAuth = nil
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLS)
		if err := Convert_v1alpha2_TLS_To_v1alpha1_TLS(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.TLS = nil
	}
	if in.KubernetesAuth != nil {
		in, out := &in.KubernetesAuth, &out.KubernetesAuth
		*out = new(KubernetesAuth)
		if err := Convert_v1alpha2_KubernetesAuth_To_v1alpha1_KubernetesAuth(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.KubernetesAuth = nil
	}
	return nil
}

// Convert_v1alpha2_Client_To_v1alpha1_Client is an autogenerated conversion function.
func Convert_v1alpha2_Client_To_v1alpha1_Client(in *v1alpha2.Client, out *Client, s conversion.Scope) error {
	return autoConvert_v1alpha2_Client_To_v1alpha1_Client(in, out, s)
}

func autoConvert_v1alpha1_Dashboard_To_v1alpha2_Dashboard(in *Dashboard, out *v1alpha2.Dashboard, s conversion.Scope) error {
	out.DashboardSpec = in.DashboardSpec
	return nil
}

// Convert_v1alpha1_Dashboard_To_v1alpha2_Dashboard is an autogenerated conversion function.
func Convert_v1alpha1_Dashboard_To_v1alpha2_Dashboard(in *Dashboard, out *v1alpha2.Dashboard, s conversion.Scope) error {
	return autoConvert_v1alpha1_Dashboard_To_v1alpha2_Dashboard(in, out, s)
}

func autoConvert_v1alpha2_Dashboard_To_v1alpha1_Dashboard(in *v1alpha2.Dashboard, out *Dashboard, s conversion.Scope) error {
	out.DashboardSpec = in.DashboardSpec
	return nil
}

// Convert_v1alpha2_Dashboard_To_v1alpha1_Dashboard is an autogenerated conversion function.
func Convert_v1alpha2_Dashboard_To_v1alpha1_Dashboard(in *v1alpha2.Dashboard, out *Dashboard, s conversion.Scope) error {
	return autoConvert_v1alpha2_Dashboard_To_v1alpha1_Dashboard(in, out, s)
}

func autoConvert_v1alpha1_Datasource_To_v1alpha2_Datasource(in *Datasource, out *v1alpha2.Datasource, s conversion.Scope) error {
	out.DatasourceSpec = in.DatasourceSpec
	return nil
}

// Convert_v1alpha1_Datasource_To_v1alpha2_Datasource is an autogenerated conversion function.
func Convert_v1alpha1_Datasource_To_v1alpha2_Datasource(in *Datasource, out *v1alpha2.Datasource, s conversion.Scope) error {
	return autoConvert_v1alpha1_Datasource_To_v1alpha2_Datasource(in, out, s)
}

func autoConvert_v1alpha2_Datasource_To_v1alpha1_Datasource(in *v1alpha2.Datasource, out *Datasource, s conversion.Scope) error {
	out.DatasourceSpec = in.DatasourceSpec
	return nil
}

// Convert_v1alpha2_Datasource_To_v1alpha1_Datasource is an autogenerated conversion function.
func Convert_v1alpha2_Datasource_To_v1alpha1_Datasource(in *v1alpha2.Datasource, out *Datasource, s conversion.Scope) error {
	return autoConvert_v1alpha2_Datasource_To_v1alpha1_Datasource(in, out, s)
}

func autoConvert_v1alpha1_DatasourceSpec_To_v1alpha2_DatasourceSpec(in *DatasourceSpec, out *v1alpha2.DatasourceSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_Datasource_To_v1alpha2_Datasource(&in.Config, &out.Config, s); err != nil {
		return err
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(v1alpha2.Client)
		if err := Convert_v1alpha1_Client_To_v1alpha2_Client(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Client = nil
	}
	return nil
}

// Convert_v1alpha1_DatasourceSpec_To_v1alpha2_DatasourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_DatasourceSpec_To_v1alpha2_DatasourceSpec(in *DatasourceSpec, out *v1alpha2.DatasourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DatasourceSpec_To_v1alpha2_DatasourceSpec(in, out, s)
}

func autoConvert_v1alpha2_DatasourceSpec_To_v1alpha1_DatasourceSpec(in *v1alpha2.DatasourceSpec, out *DatasourceSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_Datasource_To_v1alpha1_Datasource(&in.Config, &out.Config, s); err != nil {
		return err
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(Client)
		if err := Convert_v1alpha2_Client_To_v1alpha1_Client(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Client = nil
	}
	// WARNING: in.InstanceSelector requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_KubernetesAuth_To_v1alpha2_KubernetesAuth(in *KubernetesAuth, out *v1alpha2.KubernetesAuth, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_v1alpha1_KubernetesAuth_To_v1alpha2_KubernetesAuth is an autogenerated conversion function.
func Convert_v1alpha1_KubernetesAuth_To_v1alpha2_KubernetesAuth(in *KubernetesAuth, out *v1alpha2.KubernetesAuth, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubernetesAuth_To_v1alpha2_KubernetesAuth(in, out, s)
}

func autoConvert_v1alpha2_KubernetesAuth_To_v1alpha1_KubernetesAuth(in *v1alpha2.KubernetesAuth, out *KubernetesAuth, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_v1alpha2_KubernetesAuth_To_v1alpha1_KubernetesAuth is an autogenerated conversion function.
func Convert_v1alpha2_KubernetesAuth_To_v1alpha1_KubernetesAuth(in *v1alpha2.KubernetesAuth, out *KubernetesAuth, s conversion.Scope) error {
	return autoConvert_v1alpha2_KubernetesAuth_To_v1alpha1_KubernetesAuth(in, out, s)
}

func autoConvert_v1alpha1_Metadata_To_v1alpha2_Metadata(in *Metadata, out *v1alpha2.Metadata, s conversion.Scope) error {
	out.Labels = in.Labels
	out.Annotations = in.Annotations
	return nil
}

// Convert_v1alpha1_Metadata_To_v1alpha2_Metadata is an autogenerated conversion function.
func Convert_v1alpha1_Metadata_To_v1alpha2_Metadata(in *Metadata, out *v1alpha2.Metadata, s conversion.Scope) error {
	return autoConvert_v1alpha1_Metadata_To_v1alpha2_Metadata(in, out, s)
}

func autoConvert_v1alpha2_Metadata_To_v1alpha1_Metadata(in *v1alpha2.Metadata, out *Metadata, s conversion.Scope) error {
	out.Labels = in.Labels
	out.Annotations = in.Annotations
	return nil
}

// Convert_v1alpha2_Metadata_To_v1alpha1_Metadata is an autogenerated conversion function.
func Convert_v1alpha2_Metadata_To_v1alpha1_Metadata(in *v1alpha2.Metadata, out *Metadata, s conversion.Scope) error {
	return autoConvert_v1alpha2_Metadata_To_v1alpha1_Metadata(in, out, s)
}

func autoConvert_v1alpha1_OAuth_To_v1alpha2_OAuth(in *OAuth, out *v1alpha2.OAuth, s conversion.Scope) error {
	if err := Convert_v1alpha1_SecretSource_To_v1alpha2_SecretSource(&in.SecretSource, &out.SecretSource, s); err != nil {
		return err
	}
	out.ClientIDPath = in.ClientIDPath
	out.ClientSecretPath = in.ClientSecretPath
	out.TokenURL = in.TokenURL
	out.Scopes = in.Scopes
	out.EndpointParams = in.EndpointParams
	out.AuthStyle = in.AuthStyle
	return nil
}

// Convert_v1alpha1_OAuth_To_v1alpha2_OAuth is an autogenerated conversion function.
func Convert_v1alpha1_OAuth_To_v1alpha2_OAuth(in *OAuth, out *v1alpha2.OAuth, s conversion.Scope) error {
	return autoConvert_v1alpha1_OAuth_To_v1alpha2_OAuth(in, out, s)
}

func autoConvert_v1alpha2_OAuth_To_v1alpha1_OAuth(in *v1alpha2.OAuth, out *OAuth, s conversion.Scope) error {
	if err := Convert_v1alpha2_SecretSource_To_v1alpha1_SecretSource(&in.SecretSource, &out.SecretSource, s); err != nil {
		return err
	}
	out.ClientIDPath = in.ClientIDPath
	out.ClientSecretPath = in.ClientSecretPath
	out.TokenURL = in.TokenURL
	out.Scopes = in.Scopes
	out.EndpointParams = in.EndpointParams
	out.AuthStyle = in.AuthStyle
	return nil
}

// Convert_v1alpha2_OAuth_To_v1alpha1_OAuth is an autogenerated conversion function.
func Convert_v1alpha2_OAuth_To_v1alpha1_OAuth(in *v1alpha2.OAuth, out *OAuth, s conversion.Scope) error {
	return autoConvert_v1alpha2_OAuth_To_v1alpha1_OAuth(in, out, s)
}

func autoConvert_v1alpha1_Perses_To_v1alpha2_Perses(in *Perses, out *v1alpha2.Perses, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PersesSpec_To_v1alpha2_PersesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PersesStatus_To_v1alpha2_PersesStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Perses_To_v1alpha2_Perses is an autogenerated conversion function.
func Convert_v1alpha1_Perses_To_v1alpha2_Perses(in *Perses, out *v1alpha2.Perses, s conversion.Scope) error {
	return autoConvert_v1alpha1_Perses_To_v1alpha2_Perses(in, out, s)
}

func autoConvert_v1alpha2_Perses_To_v1alpha1_Perses(in *v1alpha2.Perses, out *Perses, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_PersesSpec_To_v1alpha1_PersesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_PersesStatus_To_v1alpha1_PersesStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Perses_To_v1alpha1_Perses is an autogenerated conversion function.
func Convert_v1alpha2_Perses_To_v1alpha1_Perses(in *v1alpha2.Perses, out *Perses, s conversion.Scope) error {
	return autoConvert_v1alpha2_Perses_To_v1alpha1_Perses(in, out, s)
}

func autoConvert_v1alpha1_PersesConfig_To_v1alpha2_PersesConfig(in *PersesConfig, out *v1alpha2.PersesConfig, s conversion.Scope) error {
	out.Config = in.Config
	return nil
}

// Convert_v1alpha1_PersesConfig_To_v1alpha2_PersesConfig is an autogenerated conversion function.
func Convert_v1alpha1_PersesConfig_To_v1alpha2_PersesConfig(in *PersesConfig, out *v1alpha2.PersesConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesConfig_To_v1alpha2_PersesConfig(in, out, s)
}

func autoConvert_v1alpha2_PersesConfig_To_v1alpha1_PersesConfig(in *v1alpha2.PersesConfig, out *PersesConfig, s conversion.Scope) error {
	out.Config = in.Config
	return nil
}

// Convert_v1alpha2_PersesConfig_To_v1alpha1_PersesConfig is an autogenerated conversion function.
func Convert_v1alpha2_PersesConfig_To_v1alpha1_PersesConfig(in *v1alpha2.PersesConfig, out *PersesConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_PersesConfig_To_v1alpha1_PersesConfig(in, out, s)
}

func autoConvert_v1alpha1_PersesDashboard_To_v1alpha2_PersesDashboard(in *PersesDashboard, out *v1alpha2.PersesDashboard, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_Dashboard_To_v1alpha2_PersesDashboardSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PersesDashboardStatus_To_v1alpha2_PersesDashboardStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PersesDashboard_To_v1alpha2_PersesDashboard is an autogenerated conversion function.
func Convert_v1alpha1_PersesDashboard_To_v1alpha2_PersesDashboard(in *PersesDashboard, out *v1alpha2.PersesDashboard, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesDashboard_To_v1alpha2_PersesDashboard(in, out, s)
}

func autoConvert_v1alpha2_PersesDashboard_To_v1alpha1_PersesDashboard(in *v1alpha2.PersesDashboard, out *PersesDashboard, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_PersesDashboardSpec_To_v1alpha1_Dashboard(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_PersesDashboardStatus_To_v1alpha1_PersesDashboardStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_PersesDashboard_To_v1alpha1_PersesDashboard is an autogenerated conversion function.
func Convert_v1alpha2_PersesDashboard_To_v1alpha1_PersesDashboard(in *v1alpha2.PersesDashboard, out *PersesDashboard, s conversion.Scope) error {
	return autoConvert_v1alpha2_PersesDashboard_To_v1alpha1_PersesDashboard(in, out, s)
}

func autoConvert_v1alpha1_PersesDashboardList_To_v1alpha2_PersesDashboardList(in *PersesDashboardList, out *v1alpha2.PersesDashboardList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.PersesDashboard, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_PersesDashboard_To_v1alpha2_PersesDashboard(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_PersesDashboardList_To_v1alpha2_PersesDashboardList is an autogenerated conversion function.
func Convert_v1alpha1_PersesDashboardList_To_v1alpha2_PersesDashboardList(in *PersesDashboardList, out *v1alpha2.PersesDashboardList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesDashboardList_To_v1alpha2_PersesDashboardList(in, out, s)
}

func autoConvert_v1alpha2_PersesDashboardList_To_v1alpha1_PersesDashboardList(in *v1alpha2.PersesDashboardList, out *PersesDashboardList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PersesDashboard, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_PersesDashboard_To_v1alpha1_PersesDashboard(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_PersesDashboardList_To_v1alpha1_PersesDashboardList is an autogenerated conversion function.
func Convert_v1alpha2_PersesDashboardList_To_v1alpha1_PersesDashboardList(in *v1alpha2.PersesDashboardList, out *PersesDashboardList, s conversion.Scope) error {
	return autoConvert_v1alpha2_PersesDashboardList_To_v1alpha1_PersesDashboardList(in, out, s)
}

func autoConvert_v1alpha1_PersesDashboardStatus_To_v1alpha2_PersesDashboardStatus(in *PersesDashboardStatus, out *v1alpha2.PersesDashboardStatus, s conversion.Scope) error {
	out.Conditions = in.Conditions
	return nil
}

// Convert_v1alpha1_PersesDashboardStatus_To_v1alpha2_PersesDashboardStatus is an autogenerated conversion function.
func Convert_v1alpha1_PersesDashboardStatus_To_v1alpha2_PersesDashboardStatus(in *PersesDashboardStatus, out *v1alpha2.PersesDashboardStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesDashboardStatus_To_v1alpha2_PersesDashboardStatus(in, out, s)
}

func autoConvert_v1alpha2_PersesDashboardStatus_To_v1alpha1_PersesDashboardStatus(in *v1alpha2.PersesDashboardStatus, out *PersesDashboardStatus, s conversion.Scope) error {
	out.Conditions = in.Conditions
	return nil
}

// Convert_v1alpha2_PersesDashboardStatus_To_v1alpha1_PersesDashboardStatus is an autogenerated conversion function.
func Convert_v1alpha2_PersesDashboardStatus_To_v1alpha1_PersesDashboardStatus(in *v1alpha2.PersesDashboardStatus, out *PersesDashboardStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_PersesDashboardStatus_To_v1alpha1_PersesDashboardStatus(in, out, s)
}

func autoConvert_v1alpha1_PersesDatasource_To_v1alpha2_PersesDatasource(in *PersesDatasource, out *v1alpha2.PersesDatasource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DatasourceSpec_To_v1alpha2_DatasourceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PersesDatasourceStatus_To_v1alpha2_PersesDatasourceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PersesDatasource_To_v1alpha2_PersesDatasource is an autogenerated conversion function.
func Convert_v1alpha1_PersesDatasource_To_v1alpha2_PersesDatasource(in *PersesDatasource, out *v1alpha2.PersesDatasource, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesDatasource_To_v1alpha2_PersesDatasource(in, out, s)
}

func autoConvert_v1alpha2_PersesDatasource_To_v1alpha1_PersesDatasource(in *v1alpha2.PersesDatasource, out *PersesDatasource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_DatasourceSpec_To_v1alpha1_DatasourceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_PersesDatasourceStatus_To_v1alpha1_PersesDatasourceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_PersesDatasource_To_v1alpha1_PersesDatasource is an autogenerated conversion function.
func Convert_v1alpha2_PersesDatasource_To_v1alpha1_PersesDatasource(in *v1alpha2.PersesDatasource, out *PersesDatasource, s conversion.Scope) error {
	return autoConvert_v1alpha2_PersesDatasource_To_v1alpha1_PersesDatasource(in, out, s)
}

func autoConvert_v1alpha1_PersesDatasourceList_To_v1alpha2_PersesDatasourceList(in *PersesDatasourceList, out *v1alpha2.PersesDatasourceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.PersesDatasource, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_PersesDatasource_To_v1alpha2_PersesDatasource(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_PersesDatasourceList_To_v1alpha2_PersesDatasourceList is an autogenerated conversion function.
func Convert_v1alpha1_PersesDatasourceList_To_v1alpha2_PersesDatasourceList(in *PersesDatasourceList, out *v1alpha2.PersesDatasourceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesDatasourceList_To_v1alpha2_PersesDatasourceList(in, out, s)
}

func autoConvert_v1alpha2_PersesDatasourceList_To_v1alpha1_PersesDatasourceList(in *v1alpha2.PersesDatasourceList, out *PersesDatasourceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PersesDatasource, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_PersesDatasource_To_v1alpha1_PersesDatasource(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_PersesDatasourceList_To_v1alpha1_PersesDatasourceList is an autogenerated conversion function.
func Convert_v1alpha2_PersesDatasourceList_To_v1alpha1_PersesDatasourceList(in *v1alpha2.PersesDatasourceList, out *PersesDatasourceList, s conversion.Scope) error {
	return autoConvert_v1alpha2_PersesDatasourceList_To_v1alpha1_PersesDatasourceList(in, out, s)
}

func autoConvert_v1alpha1_PersesDatasourceStatus_To_v1alpha2_PersesDatasourceStatus(in *PersesDatasourceStatus, out *v1alpha2.PersesDatasourceStatus, s conversion.Scope) error {
	out.Conditions = in.Conditions
	return nil
}

// Convert_v1alpha1_PersesDatasourceStatus_To_v1alpha2_PersesDatasourceStatus is an autogenerated conversion function.
func Convert_v1alpha1_PersesDatasourceStatus_To_v1alpha2_PersesDatasourceStatus(in *PersesDatasourceStatus, out *v1alpha2.PersesDatasourceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesDatasourceStatus_To_v1alpha2_PersesDatasourceStatus(in, out, s)
}

func autoConvert_v1alpha2_PersesDatasourceStatus_To_v1alpha1_PersesDatasourceStatus(in *v1alpha2.PersesDatasourceStatus, out *PersesDatasourceStatus, s conversion.Scope) error {
	out.Conditions = in.Conditions
	return nil
}

// Convert_v1alpha2_PersesDatasourceStatus_To_v1alpha1_PersesDatasourceStatus is an autogenerated conversion function.
func Convert_v1alpha2_PersesDatasourceStatus_To_v1alpha1_PersesDatasourceStatus(in *v1alpha2.PersesDatasourceStatus, out *PersesDatasourceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_PersesDatasourceStatus_To_v1alpha1_PersesDatasourceStatus(in, out, s)
}

func autoConvert_v1alpha1_PersesList_To_v1alpha2_PersesList(in *PersesList, out *v1alpha2.PersesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.Perses, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Perses_To_v1alpha2_Perses(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_PersesList_To_v1alpha2_PersesList is an autogenerated conversion function.
func Convert_v1alpha1_PersesList_To_v1alpha2_PersesList(in *PersesList, out *v1alpha2.PersesList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesList_To_v1alpha2_PersesList(in, out, s)
}

func autoConvert_v1alpha2_PersesList_To_v1alpha1_PersesList(in *v1alpha2.PersesList, out *PersesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Perses, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_Perses_To_v1alpha1_Perses(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_PersesList_To_v1alpha1_PersesList is an autogenerated conversion function.
func Convert_v1alpha2_PersesList_To_v1alpha1_PersesList(in *v1alpha2.PersesList, out *PersesList, s conversion.Scope) error {
	return autoConvert_v1alpha2_PersesList_To_v1alpha1_PersesList(in, out, s)
}

func autoConvert_v1alpha1_PersesService_To_v1alpha2_PersesService(in *PersesService, out *v1alpha2.PersesService, s conversion.Scope) error {
	out.Name = in.Name
	out.Annotations = in.Annotations
	return nil
}

// Convert_v1alpha1_PersesService_To_v1alpha2_PersesService is an autogenerated conversion function.
func Convert_v1alpha1_PersesService_To_v1alpha2_PersesService(in *PersesService, out *v1alpha2.PersesService, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesService_To_v1alpha2_PersesService(in, out, s)
}

func autoConvert_v1alpha2_PersesService_To_v1alpha1_PersesService(in *v1alpha2.PersesService, out *PersesService, s conversion.Scope) error {
	out.Name = in.Name
	out.Annotations = in.Annotations
	return nil
}

// Convert_v1alpha2_PersesService_To_v1alpha1_PersesService is an autogenerated conversion function.
func Convert_v1alpha2_PersesService_To_v1alpha1_PersesService(in *v1alpha2.PersesService, out *PersesService, s conversion.Scope) error {
	return autoConvert_v1alpha2_PersesService_To_v1alpha1_PersesService(in, out, s)
}

func autoConvert_v1alpha1_PersesSpec_To_v1alpha2_PersesSpec(in *PersesSpec, out *v1alpha2.PersesSpec, s conversion.Scope) error {
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(v1alpha2.Metadata)
		if err := Convert_v1alpha1_Metadata_To_v1alpha2_Metadata(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Metadata = nil
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(v1alpha2.Client)
		if err := Convert_v1alpha1_Client_To_v1alpha2_Client(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Client = nil
	}
	if err := Convert_v1alpha1_PersesConfig_To_v1alpha2_PersesConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	out.Args = in.Args
	out.ContainerPort = in.ContainerPort
	out.Replicas = in.Replicas
	out.NodeSelector = in.NodeSelector
	out.Tolerations = in.Tolerations
	out.Affinity = in.Affinity
	out.Image = in.Image
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(v1alpha2.PersesService)
		if err := Convert_v1alpha1_PersesService_To_v1alpha2_PersesService(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Service = nil
	}
	out.LivenessProbe = in.LivenessProbe
	out.ReadinessProbe = in.ReadinessProbe
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(v1alpha2.TLS)
		if err := Convert_v1alpha1_TLS_To_v1alpha2_TLS(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.TLS = nil
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(v1alpha2.StorageConfiguration)
		if err := Convert_v1alpha1_StorageConfiguration_To_v1alpha2_StorageConfiguration(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Storage = nil
	}
	out.ServiceAccountName = in.ServiceAccountName
	return nil
}

// Convert_v1alpha1_PersesSpec_To_v1alpha2_PersesSpec is an autogenerated conversion function.
func Convert_v1alpha1_PersesSpec_To_v1alpha2_PersesSpec(in *PersesSpec, out *v1alpha2.PersesSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesSpec_To_v1alpha2_PersesSpec(in, out, s)
}

func autoConvert_v1alpha2_PersesSpec_To_v1alpha1_PersesSpec(in *v1alpha2.PersesSpec, out *PersesSpec, s conversion.Scope) error {
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(Metadata)
		if err := Convert_v1alpha2_Metadata_To_v1alpha1_Metadata(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Metadata = nil
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(Client)
		if err := Convert_v1alpha2_Client_To_v1alpha1_Client(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Client = nil
	}
	if err := Convert_v1alpha2_PersesConfig_To_v1alpha1_PersesConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	out.Args = in.Args
	out.ContainerPort = in.ContainerPort
	out.Replicas = in.Replicas
	out.NodeSelector = in.NodeSelector
	out.Tolerations = in.Tolerations
	out.Affinity = in.Affinity
	out.Image = in.Image
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(PersesService)
		if err := Convert_v1alpha2_PersesService_To_v1alpha1_PersesService(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Service = nil
	}
	out.LivenessProbe = in.LivenessProbe
	out.ReadinessProbe = in.ReadinessProbe
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLS)
		if err := Convert_v1alpha2_TLS_To_v1alpha1_TLS(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.TLS = nil
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageConfiguration)
		if err := Convert_v1alpha2_StorageConfiguration_To_v1alpha1_StorageConfiguration(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Storage = nil
	}
	out.ServiceAccountName = in.ServiceAccountName
	// WARNING: in.PodSecurityContext requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_PersesStatus_To_v1alpha2_PersesStatus(in *PersesStatus, out *v1alpha2.PersesStatus, s conversion.Scope) error {
	out.Conditions = in.Conditions
	return nil
}

// Convert_v1alpha1_PersesStatus_To_v1alpha2_PersesStatus is an autogenerated conversion function.
func Convert_v1alpha1_PersesStatus_To_v1alpha2_PersesStatus(in *PersesStatus, out *v1alpha2.PersesStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PersesStatus_To_v1alpha2_PersesStatus(in, out, s)
}

func autoConvert_v1alpha2_PersesStatus_To_v1alpha1_PersesStatus(in *v1alpha2.PersesStatus, out *PersesStatus, s conversion.Scope) error {
	out.Conditions = in.Conditions
	return nil
}

// Convert_v1alpha2_PersesStatus_To_v1alpha1_PersesStatus is an autogenerated conversion function.
func Convert_v1alpha2_PersesStatus_To_v1alpha1_PersesStatus(in *v1alpha2.PersesStatus, out *PersesStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_PersesStatus_To_v1alpha1_PersesStatus(in, out, s)
}

func autoConvert_v1alpha1_SecretSource_To_v1alpha2_SecretSource(in *SecretSource, out *v1alpha2.SecretSource, s conversion.Scope) error {
	out.Type = v1alpha2.SecretSourceType(in.Type)
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_SecretSource_To_v1alpha2_SecretSource is an autogenerated conversion function.
func Convert_v1alpha1_SecretSource_To_v1alpha2_SecretSource(in *SecretSource, out *v1alpha2.SecretSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecretSource_To_v1alpha2_SecretSource(in, out, s)
}

func autoConvert_v1alpha2_SecretSource_To_v1alpha1_SecretSource(in *v1alpha2.SecretSource, out *SecretSource, s conversion.Scope) error {
	out.Type = SecretSourceType(in.Type)
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha2_SecretSource_To_v1alpha1_SecretSource is an autogenerated conversion function.
func Convert_v1alpha2_SecretSource_To_v1alpha1_SecretSource(in *v1alpha2.SecretSource, out *SecretSource, s conversion.Scope) error {
	return autoConvert_v1alpha2_SecretSource_To_v1alpha1_SecretSource(in, out, s)
}

func autoConvert_v1alpha1_StorageConfiguration_To_v1alpha2_StorageConfiguration(in *StorageConfiguration, out *v1alpha2.StorageConfiguration, s conversion.Scope) error {
	out.StorageClass = in.StorageClass
	out.Size = in.Size
	return nil
}

// Convert_v1alpha1_StorageConfiguration_To_v1alpha2_StorageConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_StorageConfiguration_To_v1alpha2_StorageConfiguration(in *StorageConfiguration, out *v1alpha2.StorageConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_StorageConfiguration_To_v1alpha2_StorageConfiguration(in, out, s)
}

func autoConvert_v1alpha2_StorageConfiguration_To_v1alpha1_StorageConfiguration(in *v1alpha2.StorageConfiguration, out *StorageConfiguration, s conversion.Scope) error {
	out.StorageClass = in.StorageClass
	out.Size = in.Size
	return nil
}

// Convert_v1alpha2_StorageConfiguration_To_v1alpha1_StorageConfiguration is an autogenerated conversion function.
func Convert_v1alpha2_StorageConfiguration_To_v1alpha1_StorageConfiguration(in *v1alpha2.StorageConfiguration, out *StorageConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha2_StorageConfiguration_To_v1alpha1_StorageConfiguration(in, out, s)
}

func autoConvert_v1alpha1_TLS_To_v1alpha2_TLS(in *TLS, out *v1alpha2.TLS, s conversion.Scope) error {
	out.Enable = in.Enable
	if in.CaCert != nil {
		in, out := &in.CaCert, &out.CaCert
		*out = new(v1alpha2.Certificate)
		if err := Convert_v1alpha1_Certificate_To_v1alpha2_Certificate(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.CaCert = nil
	}
	if in.UserCert != nil {
		in, out := &in.UserCert, &out.UserCert
		*out = new(v1alpha2.Certificate)
		if err := Convert_v1alpha1_Certificate_To_v1alpha2_Certificate(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.UserCert = nil
	}
	out.InsecureSkipVerify = in.InsecureSkipVerify
	return nil
}

// Convert_v1alpha1_TLS_To_v1alpha2_TLS is an autogenerated conversion function.
func Convert_v1alpha1_TLS_To_v1alpha2_TLS(in *TLS, out *v1alpha2.TLS, s conversion.Scope) error {
	return autoConvert_v1alpha1_TLS_To_v1alpha2_TLS(in, out, s)
}

func autoConvert_v1alpha2_TLS_To_v1alpha1_TLS(in *v1alpha2.TLS, out *TLS, s conversion.Scope) error {
	out.Enable = in.Enable
	if in.CaCert != nil {
		in, out := &in.CaCert, &out.CaCert
		*out = new(Certificate)
		if err := Convert_v1alpha2_Certificate_To_v1alpha1_Certificate(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.CaCert = nil
	}
	if in.UserCert != nil {
		in, out := &in.UserCert, &out.UserCert
		*out = new(Certificate)
		if err := Convert_v1alpha2_Certificate_To_v1alpha1_Certificate(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.UserCert = nil
	}
	out.InsecureSkipVerify = in.InsecureSkipVerify
	return nil
}

// Convert_v1alpha2_TLS_To_v1alpha1_TLS is an autogenerated conversion function.
func Convert_v1alpha2_TLS_To_v1alpha1_TLS(in *v1alpha2.TLS, out *TLS, s conversion.Scope) error {
	return autoConvert_v1alpha2_TLS_To_v1alpha1_TLS(in, out, s)
}
