name: docs
on:
  push:
    branches:
      - main
      - release/*
      - snapshot/*
    tags:
      - v*
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref_name != 'main' }}

jobs:
  changed-files:
    uses: ./.github/workflows/changed-files.yaml

  check-api-docs:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.api == 'true' }}
    name: 'check API docs are up-to-date'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: perses/github-actions@98d861448dd5b9b3ac9dcefe377323a913ecbb83 # v0.13.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
      - name: Install all tools
        uses: ./.github/tools-cache
      - name: check API docs are up-to-date
        run: make check-api-docs

  check-metrics-docs:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.metrics_docs == 'true' }}
    name: 'check metrics docs are up-to-date'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - uses: perses/github-actions@v0.13.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
      - name: Install all tools
        uses: ./.github/tools-cache
      - name: check metrics docs are up-to-date
        run: make check-metrics-docs

  check-docs:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.docs == 'true' }}
    name: 'check markdown formatting and links'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: perses/github-actions@98d861448dd5b9b3ac9dcefe377323a913ecbb83 # v0.13.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
      - name: Cache links for mdox
        uses: ./.github/actions/mdox-cache
      - name: Install all tools
        uses: ./.github/tools-cache
      - name: format docs
        run: make fmt-docs
      - name: check docs are up-to-date
        run: git diff --exit-code
